In [1]:
import numpy as np

In [3]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print (X)

[[ -1.69782906  10.36762573  -5.18097129 ..., -20.75990193  -2.89887349
   -0.06567641]
 [ 16.56703645 -22.05196155   4.65242108 ...,   3.1551943   11.63846849
    6.91975556]
 [ -9.26213051   8.36855058 -12.35347205 ...,   1.45093041   8.40859917
  -14.3226627 ]
 ..., 
 [ -6.361987     9.5713288    6.87023243 ...,  11.16547081   2.02235643
   -0.18588858]
 [ -9.66912804  21.42441974  -0.29348722 ...,   3.27723164   7.4334893
    3.33277904]
 [  3.9811001   -4.54033576 -12.12078047 ..., -16.04439523   5.98050426
    3.28627688]]


In [15]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print(X_norm)
b = np.median(X)
print(b)

[[-0.27793661  0.92432775 -0.68076314 ..., -2.18439799 -0.3739165
  -0.06458236]
 [ 1.53024583 -2.2809411   0.35755091 ...,  0.26655154  1.06635229
   0.65486036]
 [-1.0267862   0.72668262 -1.43811199 ...,  0.09188928  0.74635707
  -1.53293609]
 ..., 
 [-0.73967823  0.84559924  0.591731   ...,  1.08748837  0.11364814
  -0.07696324]
 [-1.06707809  2.01749396 -0.16469064 ...,  0.27905859  0.64974929
   0.28543093]
 [ 0.28426517 -0.54959677 -1.41354194 ..., -1.70112714  0.50579664
   0.28064159]]
0.922401642507


In [5]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
print(Z)

[[4 5 0]
 [1 9 3]
 [5 1 1]
 [3 3 3]
 [9 9 9]
 [4 7 1]]


In [6]:
r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5], dtype=int64),)


In [12]:
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)
AB = np.vstack((A,B))
print(AB)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
